# Kerran 5 Tehtävät

### Leevi Kukkonen K8397

## Tehtävä 1

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

## Tehtävä 2

In [7]:
import numpy as np
import pandas as pd
# T2
df = pd.read_csv('https://student.labranet.jamk.fi/~varpe/datananalk2019/kerta4/kysely.csv')

#  tjohto/sukupuoli jakauma
pd.crosstab(df['sukup'], df['Tjohto'])
df

,nro,sukup,ikä,perhe,koulutus,palveluv,Tjohto,Ttyöteht,työterveys,liikunta,lomaosake
0,1,nainen,38,perheetön,1.0,22.0,3,3,NaN,NaN,NaN
1,2,nainen,29,perheellinen,2.0,10.0,1,3,NaN,NaN,NaN
2,3,mies,30,perheetön,1.0,7.0,3,3,1.0,NaN,NaN
3,4,mies,36,perheellinen,1.0,14.0,3,3,1.0,NaN,NaN
4,5,nainen,24,perheetön,2.0,4.0,2,2,1.0,NaN,NaN
5,6,mies,31,perheellinen,2.0,14.0,4,4,1.0,1.0,NaN
6,7,mies,49,perheetön,2.0,16.0,3,2,NaN,NaN,1.0
7,8,mies,55,perheetön,1.0,0.0,3,3,1.0,NaN,NaN
8,9,mies,40,perheellinen,1.0,23.0,2,4,NaN,1.0,NaN
9,10,mies,33,perheetön,1.0,16.0,3,1,1.0,NaN,NaN
10,11,nainen,39,perheellinen,1.0,22.0,3,3,NaN,NaN,NaN
11,12,mies,40,perheellinen,3.0,21.0,3,2,NaN,1.0,NaN
12,13,mies,35,perheellinen,3.0,15.0,3,4,NaN,1.0,NaN
13,14,mies,58,perheellinen,3.0,21.0,4,3,NaN,NaN,NaN
14,15,mies,53,perheellinen,3.0,12.0,4,4,NaN,1.0,NaN
15,16,mies,42,perheellinen,3.0,23.0,3,3,1.0,NaN,NaN
16,17,mies,26,perheetön,4.0,2.0,5,5,NaN,NaN,1.0
17,18,mies,38,perheellinen,3.0,17.0,4,1,NaN,NaN,NaN
18,19,mies,42,perheetön,3.0,20.0,2,4,1.0,NaN,NaN
19,20,mies,40,perheellinen,2.0,13.0,3,2,1.0,NaN,NaN
20,21,mies,40,perheellinen,3.0,20.0,2,4,NaN,NaN,NaN
21,22,nainen,47,perheellinen,3.0,17.0,2,4,NaN,1.0,NaN
22,23,mies,44,perheellinen,1.0,27.0,4,4,NaN,1.0,NaN
23,24,mies,36,perheetön,3.0,7.0,3,5,NaN,NaN,NaN
24,25,mies,43,perheellinen,3.0,1.0,4,4,NaN,1.0,NaN
25,26,nainen,26,perheetön,2.0,3.0,2,3,1.0,NaN,1.0
26,27,nainen,26,perheetön,2.0,2.0,2,3,1.0,NaN,NaN
27,28,mies,56,perheetön,1.0,15.0,3,4,1.0,NaN,NaN
28,29,nainen,47,perheellinen,2.0,23.0,2,4,1.0,NaN,NaN
29,30,mies,21,perheetön,NaN,NaN,4,2,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
52,53,mies,44,perheellinen,1.0,3.0,1,1,1.0,NaN,NaN
53,54,mies,25,perheetön,2.0,1.0,2,2,1.0,NaN,NaN
54,55,nainen,45,perheellinen,1.0,17.0,3,3,NaN,NaN,NaN
55,56,nainen,31,perheellinen,1.0,6.0,4,3,1.0,NaN,NaN
56,57,mies,61,perheellinen,2.0,36.0,2,5,1.0,NaN,NaN
57,58,mies,38,perheellinen,2.0,NaN,2,2,1.0,NaN,NaN
58,59,mies,20,perheetön,2.0,1.0,3,3,NaN,NaN,NaN
59,60,mies,31,perheetön,1.0,10.0,4,3,1.0,NaN,NaN
60,61,mies,44,perheetön,1.0,19.0,2,2,1.0,NaN,NaN
61,62,mies,40,perheellinen,1.0,0.0,2,3,1.0,NaN,NaN
62,63,nainen,51,perheellinen,2.0,10.0,4,3,1.0,NaN,NaN
63,64,nainen,44,perheetön,2.0,1.0,4,3,1.0,NaN,NaN
64,65,nainen,35,perheellinen,2.0,17.0,4,4,1.0,NaN,NaN
65,66,nainen,37,perheellinen,1.0,16.0,5,5,1.0,1.0,NaN
66,67,mies,37,perheellinen,4.0,8.0,3,2,1.0,1.0,NaN
67,68,mies,33,perheellinen,3.0,7.0,2,4,NaN,NaN,NaN
68,69,mies,28,perheellinen,2.0,1.0,4,4,NaN,NaN,NaN
69,70,mies,52,perheellinen,2.0,22.0,3,2,1.0,1.0,NaN
70,71,mies,34,perheellinen,2.0,1.0,3,4,NaN,1.0,NaN
71,72,mies,46,perheellinen,2.0,23.0,3,4,NaN,1.0,NaN
72,73,nainen,40,perheellinen,3.0,2.0,5,4,1.0,NaN,NaN
73,74,mies,45,perheellinen,1.0,20.0,3,3,1.0,NaN,NaN
74,75,mies,40,perheetön,1.0,1.0,1,1,1.0,NaN,NaN
75,76,mies,37,perheetön,2.0,15.0,1,1,1.0,NaN,NaN
76,77,mies,39,perheetön,2.0,22.0,4,2,NaN,NaN,NaN
77,78,mies,22,perheetön,3.0,0.0,4,4,NaN,1.0,1.0
78,79,mies,33,perheetön,1.0,2.0,1,2,1.0,NaN,NaN
79,80,mies,27,perheetön,2.0,7.0,3,3,1.0,NaN,1.0
80,81,mies,35,perheellinen,2.0,16.0,3,3,NaN,NaN,NaN
81,82,nainen,35,perheellinen,3.0,15.0,3,4,1.0,NaN,NaN

In [18]:
import numpy as np
import pandas as pd
# prosenttiosuudet: koulutus, tyytyväisyys johtoon,
koulu = ({'perusasteen koulutus', 'keskiasteen koulutus', 'alempi korkeakoulutus', 'ylempi korkeakoulutus'})
pd.crosstab(df['koulutus'], df['Ttyöteht'], normalize='index').applymap("{:.1%}".format)

Ttyöteht      1      2      3      4      5
koulutus
1.0       11.1%  11.1%  48.1%  22.2%   7.4%
2.0        3.3%  26.7%  33.3%  23.3%  13.3%
3.0        4.5%   9.1%  27.3%  54.5%   4.5%
4.0        0.0%  50.0%   0.0%   0.0%  50.0%

## Tehtävä 3

In [ ]:
#T3

## Tehtävä 4

In [ ]:
#T4

# Tehtävä 5